language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: eNFR1EextxztfQw9L2Ia5D0Gbd60iQTpnCxzVMbSiqsox0O45FJjgEIZ7h3+G8I9CzVHiLX8JDCY3W+lGnxo9bZiJZEmKGjFp4cIrYLymazBaQVxoS/Q5g5kjIbeFR33vLIMiNt1BLE7jTZH+erSVuXS8l8TOoFsAogpVURhnLzHP3YItVYSBQgwJk2KvSq5dbP9dxlM7lf7+jWFmQ5P7TebG5YlQNQdF8WVyOBd1dMW96I/acZqfZY/lIPnyCY5SFJHRNJPSEuEt+wPBKG1t4qqYIZMHmmt++uzERhXl0JDmHNl9gNB3l5lg5H1nu5bLH60zLRx+obj+J9MVPAP8cgVE6j2CETfKHQJCryaWFp4xgBgMTYe4jBxweZyJNQdEnXSzPJaxMyUQWMCz6FEPZoaPSZSytWe0OP4gACG0GYIWmMFHJH/cQWgslyJCVHUzKZdKoj8/qzzn8SNGRyXpGYD/czl4psj49+vfURIMWHG+cXSEanPzvpX7XEHG4m2OId3ufuIGHYlo/wAc/JVpW6/nlGUaUCH/ZnqPgK/1lb+087Qp/TNpnbzXwREXFUd7e5kX8j7ZhcU171ZSm5V8NE9ZRhQB6UWHzQt8c/mIK+eXGVRQ3lTOebfC2xkBkpHY/n7+ZinxeHHw/fw0hLuzXo/SB/0wo+fh8vMWeiC9IA=
  app: worksend
  on:
    repo: davideuez/WorkSend
