language: node_js
node_js:
- '8'

deploy:
  provider: heroku
  api_key:
    secure: bpyxPQQt+n5ucx7GQp/VoOgeybDBntW2XcOQV7/JHi1OzibBqeP1iY2HtyTu3n0iG4PNL/+FALbb8sJB0xM+393+e3Cv6NsD/OYJMk2sRprM634Kzlxb53sf2I5kIVtasdfoIohXYcFBmqJbC7HBVH1EwHxHEFWVE64vCwC/v2LsUQOgJgQKneOJASu1aOxdrluUedz3FmFt07rjAVvbgNVpprxitUR8mRRRjBMC1zvnJs4/nS3MURUIaYG2SAdxP3mjUEfVFql0uUqhkj30rh3VITSbbifDgyKm5aBS7VUwLSnSdTPla4lfaeyB1ecoBqEGYkiBfCkUxYHiBMtXpy8OMyAaBBuWpYXKTyhi7Z5e5f4Qh7hJMx7ovdkgqHUqqT3d4pPqNISa6ewXcubK+dfDjEXXkz9QV5gOOGmLEBXbdsm1NvUKGBgKz16sfmOLLC+x+ZsavUDTSXLDNsm+PrqpnO7+4BziagmubnrXnflaWb1658tHujVeLlJvnHI0Anazmk/WhrBqBIt+QWlBhpl/t6/fu5jqNIEmqhnmNVkZuuNMzSpMygRggdYXehxRdMzsHep5oXb60xg1KJvwZJAkZb3rZlzq6mvowMu6cweBvGOwnZ33kmYEa51ndieQORxf2JiqRT13UmgojZCrvLwvo/98H0tO227AZNXozbY=
  app: worksend
