language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: "WuuV8K837waUHJGKhj9pasvMl4x2k2Nti0vhSUSMft68YfN2fK640nI40xiX2glzulsa/X7cgMx2YkX1irL29ZjaRt5XFRDG3ujO4ABQW8Z2jQcHRwjkj7WLdTD+snTQB5m/owMFf90BT6cv7Kr3P2yOPqwwCtVLQlfAq5wXA6HjXAawYEAT9MUbEVueOVFMWBwlUakSkOeWteSnVXGnV7LdxaZnxacwv73jtuStOqem0UuzeOMWDfX9L+m7LX2j0cbG18xVtnS8axjellY4Wds1xfFXe1WmNizvhcmZ+7tI76CAXGS5RBotlnYk824jocd+6VdZ3QzfUZenQoGCYM58R+V3EBo5uDdKIv6pjsnP+3bk0OyK1cXUA+saFWhVV2FRsUszsd4bvKyakQHZSlrv9jjC8nmZfQNNVa0G7DzbrkGRi54B2stEvH/DmVB5wN9VhWFZQCdltcpYW5CF+BAaYl01yx+AG6ugOQI8WHwWCcExi9RBqqISOeEtMqEAm+rnnMUt4UoblNsUyeuaIRLLWkCt2uqBn+vT8Td74yiBcLLZFvIdLDXBli9NG00iZjukVMaYPnAzVTGr6VhynRi7hDsOexhbwpmljlzxvPPyb9Upe7+UFhx7V88oA6WiV9qTlOlgdxuxmlddJysGPt8kQYdzY2KqFnQSMdabp1c="
  app: worksend
    
