language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: "TpJ+SfYHy5fGZ3vuIyVCTQmPgnoEWgqGiPfbZDatHA1cTgRhP+vTP4bwYsyWyGRz/XwWZz1TGuQEdmUqMJjJRJMlvjiQwHsS7/IoVs9k16pzqHe0ipQZGlKsAmNeFT+Ba74+Ywpzk9YqDIoP+V981K6feu8dUPwhJxnKF6815ywWNV7Ec95WMCb8HB65apPbgVcuwoPQe4geh9WXULXCRpGozj0w73sX07q3SGVGY7jUrLNSde2DEXY939wewKJ2ETnCalLc2iMRF6XW03emSiE1E1WB51ED9LtcY3wcjlXPpQvEOhbyovS3u0ce327LfYjSV9dqvZpwu3uhyLQ9fs8Ee0Bd+4ul8grste4zaeKzjkxhwhgjoIP50DPDEhy0jLRPKvZqLM1yKLGwE0xjdKu9zdKzUWG9JumZnLXqS2Hxaz0VbIu3Q0lP3/FG5C85hXkYG8qiD/X2urZPqDqL61bYHhriMI2MAfQ6TMWyiI4cOOxqT972sOxZT9GMGVLlFXdTBTShKGBxcrzDN1U++KxoouzHgPFNZbnNT9gQ7IJQrJoeuL1NVwsr94xkf7pqRTztFshwfAPoMsKwXvupmgGHZhPyX0nr4fNMTaDZTaUO3d8qX2xJKyJ12Taut6Jr0VZlJYXoBYb4/Gn0MWe1YrFpPndjCgJ5N7mnZXPhsac=" 
  app: worksend
