language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: qoYcJ667w9O6S5TClaBbAvQq2kDzR1HCmZj9cGvNDGsQuqX8rIzS5gWItvTY4OwiTPFIgKApPgNmNWSXcB6QknfKn4m3pj7XdzX6dZT1R+zNg/eX8iwZxjpkIkrIT7kEKjyhA9PqWYb0EmyzevKbe/SVJ3h3L9KWEOPZv9oD2VY8ViD5YSD6fwTJ+Cg1aa2s499Ft1J2L/9w0ualE8UFqqFlaQAyPmJLAkgVqvO5vIymjAxg39I+4rcOYwJ7oCxFv7VKpQ8pMywWl4mJRir3CxOebWeAB+iG8DQk+1LV0ZCVKHW8R4W9uHk06fDnlgM5eKpeeH9lQ5nKpDMFHgdnxyo3CoxyS1D/OJ4Ml5w1+LI8CupNj4VUCMYwkUK8XPSgP4zqgBFcy96sByuiDLAIsCRMJdLKnWKEaP1zlyZuLAXGPseczW9Hme6YQ6OJvC8vxz4okbvYvSjXSMdfhTLZGu8iwt8lV0n8PxT5pCFr9cCL3xFaYnvP1F21ESwAZfWTlxU9Q+ud4T7UVJ+peuPOfIMr3yA20yDrWeHZ9D6+lMkAeZVozDXginOiV2/2Pr0+vcUd6gj8qgQRT7/92C6TK/aTicOqQ+0Avq3avBLVy2Ub9Udi2h8DycJjXqGUsT1hWVfHqbFdaVGjE6utpJmmfGdWssQRp99WjQblADfvquU=
  app: WorkSend
  on:
    repo: davideuez/WorkSend
