language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: iEOOPujtWuq2Oi1SzD+l2Vz0hCSCjnLd6/Y8cfUPxheLNXHTxI4TtNWLeUPQ4cw6SiacgV+o+fND+J/1jmrRX3qp2p5HXkth/nRUdNhj4V6dIBcDA+3PQkvSa9qFD+i1ngb9B9edZYnpK6GugpPfjLKi4gVRxVZpyG6RIFp7W7wbhLB2EJSl5JwD11KGdF0fUMCq/UmhfBUzixX0L+W/8xGWI+0G7gNmBuc97HmVOuMu3q1sI+GYOrB9WJ8SjqQCUm4NfQdx1lfZcU/fCX8siOwLFsCIxSuUCfXm6xjX0fPoa0AbK/9mJmA//CG/G64kQvpFHAiezuhL+chI48QUKXL7B5qlUkNkNS4IlBsEToyn9AX/JUu/OD4f9luNlCnAGTrhCPN824ba4w0b/sX5POUVNxim4SlcFpye3ruEGVlFI/XvaEdguSmBaBX9A9wX3bY69f9wiVEr+B+HH/npYBgsvnkTVHYHJunYijbsHc3C46aTqUQxwPJ1QzD6XyK3N2mPJ5f6+2wYEc/xv+gVclhqGZlyLrcTkrNXdYlqoZp+e0vj4/UfJY5V2cUscMdbO/kJw0AGp1cAklBQGP0xEFPJdQnhimCF0yGYP+NpUwKdqQ/Rd8Zz2EZ7rkybObceAlOYBCfhqtNLlXg+XBMiWDszg+Zn494M9PezJxcHoSM=
  app: worksend
